Rebuild configure.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -25100,16 +25100,22 @@ else $as_nop
 then :
   if test x${PYTHON_SPHINXB} = x
 then :
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: missing the sphinx module, python documentation cannot not be built" >&5
-printf "%s\n" "$as_me: WARNING: missing the sphinx module, python documentation cannot not be built" >&2;}
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: missing the sphinx-build, python documentation cannot not be built" >&5
+printf "%s\n" "$as_me: WARNING: missing the sphinx-build, python documentation cannot not be built" >&2;}
+else $as_nop
+  if test x${PYTHON_SPHINXA} = x
+then :
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: missing the sphinx-apidoc, python documentation cannot not be built" >&5
+printf "%s\n" "$as_me: WARNING: missing the sphinx-apidoc, python documentation cannot not be built" >&2;}
 else $as_nop
   if test x${PYTHON_BREATHE} = x
 then :
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: missing the breathe module, python documentation cannot not be built" >&5
-printf "%s\n" "$as_me: WARNING: missing the breathe module, python documentation cannot not be built" >&2;}
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: missing the breathe-apidoc, python documentation cannot not be built" >&5
+printf "%s\n" "$as_me: WARNING: missing the breathe-apidoc, python documentation cannot not be built" >&2;}
 else $as_nop
   HAVE_PYTHON_DOCS=1
 
+fi
 fi
 fi
 fi
